((magit-blame ("-w"))
 (magit-branch nil)
 (magit-cherry-pick ("--ff"))
 (magit-commit nil)
 (magit-diff ("--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log ("-n256" "--graph" "--decorate") (("--" "simplex/sales_order_cmd_generator.go")) ("-n256" "--graph" "--color" "--decorate"))
 (magit-merge nil ("--ff-only"))
 (magit-pull nil)
 (magit-push nil ("--force-with-lease") ("--force"))
 (magit-rebase nil)
 (magit-reset nil)
 (magit-show-refs nil)
 (magit-stash nil)
 (magit-submodule nil))
